# Generated by Django 6.0.4 on 2026-04-15 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Ilac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilac_adi', models.CharField(db_index=True, max_length=200, verbose_name='İlaç Adı')),
                ('barkod', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barkod / Karekod')),
                ('stok_miktari', models.IntegerField(default=0, verbose_name='Stok Miktarı')),
                ('kritik_stok_esigi', models.IntegerField(default=10, verbose_name='Kritik Stok Eşiği')),
                ('son_kullanma_tarihi', models.DateField(blank=True, db_index=True, null=True, verbose_name='Son Kullanma Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilaclar', to='stok.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'İlaç',
                'verbose_name_plural': 'İlaçlar',
                'ordering': ['ilac_adi'],
            },
        ),
        migrations.CreateModel(
            name='Recete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasta_ad_soyad', models.CharField(max_length=100, verbose_name='Hasta Adı Soyadı')),
                ('hasta_tc', models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik No')),
                ('doktor_ad_soyad', models.CharField(max_length=100, verbose_name='Doktor Adı Soyadı')),
                ('doktor_diploma_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Doktor Diploma No')),
                ('recete_tarihi', models.DateField(db_index=True, verbose_name='Reçete Tarihi')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('teslim_edildi', 'Teslim Edildi')], db_index=True, default='bekliyor', max_length=20, verbose_name='Durum')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receteler', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden Personel')),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
                'ordering': ['-recete_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='StokHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField(verbose_name='Miktar')),
                ('islem_tipi', models.CharField(choices=[('giris', 'Giriş'), ('cikis', 'Çıkış'), ('satis', 'Satış')], db_index=True, max_length=20, verbose_name='İşlem Tipi')),
                ('aciklama', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='İşlem Tarihi')),
                ('ilac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hareketler', to='stok.ilac', verbose_name='İlaç')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stok_hareketleri', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-islem_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='ReceteIlac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanilan_miktar', models.IntegerField(default=1, verbose_name='Kullanılan Miktar')),
                ('talimat', models.TextField(blank=True, null=True, verbose_name='Kullanım Talimatı')),
                ('ilac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recete_satirlari', to='stok.ilac', verbose_name='İlaç')),
                ('recete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recete_ilaclar', to='stok.recete', verbose_name='Reçete')),
            ],
            options={
                'verbose_name': 'Reçete İlacı',
                'verbose_name_plural': 'Reçete İlaçları',
                'unique_together': {('recete', 'ilac')},
            },
        ),
    ]
